<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE BookCatalog[
   <!ELEMENT BookCatalog (Book*)>
  <!ELEMENT Book (title, description*, author, year, publisher)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
  <!ELEMENT year (#PCDATA)>
  <!ELEMENT publisher (#PCDATA)>
]>

<BookCatalog>
  <Book>
    <title>XML프로그래밍</title>
    <description>체계적으로 배우는 XML원리와 응용</description>
    <author>홍성용</author>
    <year>2015</year>
    <publisher>한빛아카데미</publisher>
  </Book>
  <Book>
    <title>소프트웨어공학</title>
    <description>10판</description>
    <author>권기태, 노정규 외</author>
    <year>2016</year>
    <publisher>한티미디어</publisher>
  </Book>
  <Book>
    <title>인공지능개론</title>
    <author>마이클 네그네빗스키, 김용혁</author>
    <year>2015</year>
    <publisher>한빛아카데미</publisher>
  </Book>
</BookCatalog>